name: 'Setup'

description: 'Sets up project dependencies'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2.4.0

    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: pnpm

    - run: pnpm install
      shell: bash
