name: 'Setup'

description: 'Sets up project dependencies'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2.2.2

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: pnpm

    - name: Install docker-compose v2 (GH actions used v1 by default)
      shell: bash
      run: |
        VERSION="v2.5.1"
        INSTALL_PATH="$HOME/.local/bin/docker-compose"
        DOWNLOAD_URL="https://github.com/docker/compose/releases/download/${VERSION}/docker-compose-$(uname -s)-$(uname -m)"
        mkdir -p "$(dirname $INSTALL_PATH)" || true
        curl -fsSL "$DOWNLOAD_URL" -o "$INSTALL_PATH"
        chmod +x "$INSTALL_PATH"

    - run: pnpm install
      shell: bash
