name: 'Setup'

description: 'Sets up project dependencies'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2.2.1

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: pnpm

    - shell: bash
      run: |
        echo "$PATH"
        VERSION=v2.5.1
        INSTALL_PATH=/usr/local/bin/docker-compose
        curl \
          -fsSL "https://github.com/docker/compose/releases/download/${VERSION}/docker-compose-$(uname -s)-$(uname -m)" \
          -o $INSTALL_PATH
        chmod +x $INSTALL_PATH

    - run: pnpm install
      shell: bash
