services:
  # Local NPM registry
  registry:
    image: ehyland/verdaccio-test:5.30.3
    environment:
      - VERDACCIO_UID
      - VERDACCIO_PORT
    volumes:
      - ./test/e2e/verdaccio/storage/data:/verdaccio/storage/data
    ports:
      - ${VERDACCIO_PORT}:${VERDACCIO_PORT}

  # For building and publishing to a local registry
  builder:
    build:
      dockerfile: test/e2e/Dockerfile.builder
      context: .
    network_mode: service:registry
    environment:
      - LOCAL_NPM_REGISTRY=http://localhost:48733/
    volumes:
      - ./packages/pmm/src:/app/packages/pmm/src

  # NodeJS test environment
  tester:
    build:
      dockerfile: test/e2e/Dockerfile.tester
      context: .
      args:
        - NODE_TEST_VERSION=${NODE_TEST_VERSION}
    network_mode: service:registry
    environment:
      - LOCAL_NPM_REGISTRY=http://localhost:48733/
    volumes:
      - ./test:/app/test
