#!/bin/bash

set -euo pipefail

# config
PUBLISH_ARGS=""

if [[ -n "$1" ]]; then
  PUBLISH_ARGS+=" --tag=$1"
fi

pnpm build

pnpm changeset publish \
  --registry="https://registry.npmjs.org/" \
  $PUBLISH_ARGS
