#!/bin/bash

set -euo pipefail

VERSION_ARGS=""

if [[ -n "${1-}" ]]; then
  VERSION_ARGS+=" --snapshot=$1"
fi

pnpm changeset version $VERSION_ARGS

pnpm install --lockfile-only

pnpm format:write


