#!/bin/bash

set -euo pipefail

# get initial version
initial_version=`cat ./package.json | jq -r .version`

function clean_up {
  # revert version change
  pnpm version \
    --allow-same-version \
    --no-git-tag-version \
    $initial_version
}
trap clean_up EXIT

# update version
new_version=$(
  pnpm version \
    --allow-same-version \
    --no-git-tag-version \
    "$initial_version-latest-local.$(date +%s)"
)

pnpm build
pnpm publish \
  --no-git-checks \
  --registry http://localhost:4873 \
  --tag "latest"

