#!/bin/bash

set -euo pipefail

if [[ -z "${IS_CHILD_PROCESS:-}" ]]; then
  echo "IS_CHILD_PROCESS=1 pnpm -r exec $(realpath $0)"
  exit 0
fi

# get initial version
initial_version=`cat ./package.json | jq -r .version`

function clean_up {
  # revert version change
  pnpm version \
    --allow-same-version \
    --no-git-tag-version \
    $initial_version
}
trap clean_up EXIT

# update version
new_version=$(
  pnpm version \
    --allow-same-version \
    --no-git-tag-version \
    "$initial_version-latest-local.$(date +%s)"
)

pnpm build
pnpm publish \
  --no-git-checks \
  --registry http://localhost:4873 \
  --tag "latest"

