#!/bin/bash

set -euo pipefail

if [[ -z "${IS_CHILD_PROCESS:-}" ]]; then
  pnpm build
  IS_CHILD_PROCESS=1 pnpm -r exec $(realpath $0)
  exit 0
fi

LOCAL_NPM_REGISTRY="${LOCAL_NPM_REGISTRY:-"http://localhost:48733/"}"

# get initial version
package_name=`cat ./package.json | jq -r .name`
initial_version=`cat ./package.json | jq -r .version`

function clean_up {
  # revert version change
  pnpm version \
    --allow-same-version \
    --no-git-tag-version \
    $initial_version
}
trap clean_up EXIT

# update version
new_version=$(
  pnpm version \
    --allow-same-version \
    --no-git-tag-version \
    "$initial_version-latest-local.$(date +%s)"
)

pnpm publish \
  --no-git-checks \
  --registry "$LOCAL_NPM_REGISTRY" \
  --tag "latest"

echo "🚀 Published $package_name@$new_version"
