#!/bin/bash

set -euo pipefail

function clean_up {
  docker compose down
}
trap clean_up EXIT

# export for use in docker-compose.yml
export NODE_TEST_VERSION="${NODE_TEST_VERSION:-20}"
export VERDACCIO_UID=`id -u`
export VERDACCIO_PORT="48733"

BUILD_WATCH="${BUILD_WATCH:-}"
EXTRA_JEST_ARGS=""
TTY_ARGS=""

if [ -t 1 ]; then
  echo "Running in interactive mode"
  TTY_ARGS="-it"
fi

# Clear previous builds
rm -rf test/e2e/verdaccio/storage/data/@ehyland/pmm || true

docker compose pull
docker compose build

docker compose up -d registry

last_message=""
function say_once {
  message="$@"
  if [[ "$message" == "$last_message" ]]; then
    printf "."
  else
    last_message="$message"
    printf "\n$message"
  fi
}

if [[ -n "$BUILD_WATCH" ]]; then
  echo ""
  echo "⚠️  Make sure you run \"pnpm build:watch:release\" in another console"
  while true; do

    package_status=$(
      curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:48733/@ehyland/pmm/latest || true
    )

    if [[ "$package_status" == "000" ]]; then 
      say_once "waiting for registry to boot"
    elif [[ "$package_status" == "404" ]]; then
      say_once "waiting for package to be published"
    elif [[ "$package_status" == "200" ]]; then
      say_once "package found"
      break;
    else
      say_once "unexpected status $package_status"
    fi

    sleep 1
  done
  
  echo ""

  EXTRA_JEST_ARGS+=" --watchAll"
else
  docker compose run --rm $TTY_ARGS builder ./scripts/docker/builder-entrypoint
fi

docker compose run --rm $TTY_ARGS tester \
  pnpm jest \
    --runInBand \
    --verbose \
    --config ./jest.config.e2e.js $EXTRA_JEST_ARGS