#!/bin/bash

set -euo pipefail

ENV="${ENV:-node-16}"

docker-compose build "$ENV"

docker-compose run --rm -it "$ENV" \
  pnpm jest \
    --runInBand \
    --verbose \
    --config ./jest.config.e2e.js $@