#!/bin/bash

set -euxo pipefail

docker build -t local/node-16 -f $(dirname $0)/Dockerfile.node-16 .

docker run \
  --rm \
  -v "${PWD}/packages:/app/packages" \
  -v "${PWD}/test:/app/test" \
  local/node-16 $@
