on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - e2e-tests
    steps:
      - run: echo "🚀"

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: pnpm build

      - run: pnpm test

  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [18, 20]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: pnpm test:e2e
        env:
          NODE_TEST_VERSION: ${{ matrix.version }}
