on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - e2e-tests
    steps:
      - run: echo "🚀"

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - run: pnpm build

      - run: pnpm test

  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [14, 16, 18]
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - uses: actions/cache@v3
        with:
          path: test/e2e/verdaccio/storage/data
          key: ${{ runner.os }}-verdaccio

      - run: pnpm test:e2e
        env:
          NODE_TEST_VERSION: ${{ matrix.version }}
