on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - run: pnpm build

      - run: pnpm test

      # - if: ${{ jobs.e2e-tests.status == "success" }}
      - run: |
          if [[ "${{ jobs.e2e-tests.status }}" == "success" ]]; then
            exit 0
          else
            exit 1
          fi

  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [14, 16, 18]
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - run: pnpm test:e2e
        env:
          NODE_TEST_VERSION: ${{ matrix.version }}
