on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - run: pnpm build

      - run: pnpm test

      - run: pnpm test:e2e
